name: QA Challenge CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        working-directory: ./qa-backend-task
        run: npm ci

      - name: Start backend
        working-directory: ./qa-backend-task
        run: |
          npm start &
        env:
          CI: true

      - name: Wait for backend to be ready
        run: npx wait-on http://localhost:5000

      - name: Install frontend dependencies
        working-directory: ./qa-frontend-task
        run: npm ci

      - name: Start frontend
        working-directory: ./qa-frontend-task
        run: |
          npm start &
        env:
          CI: true

      - name: Wait for frontend to be ready
        run: npx wait-on http://localhost:3000

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: ./qa-frontend-task
          start: npm start
          wait-on: http://localhost:3000
