name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install wait-on
        run: npm install -g wait-on

      - name: Install backend dependencies
        working-directory: qa-backend-task
        run: npm install

      - name: Install frontend dependencies
        working-directory: qa-frontend-task
        run: npm install

      - name: Start backend
        working-directory: qa-backend-task
        run: npm start &
      
      - name: Start frontend
        working-directory: qa-frontend-task
        run: npm start &

      - name: Wait for frontend to be ready
        run: wait-on http://localhost:3000

      - name: Wait for backend to be ready
        run: wait-on http://localhost:5001

      - name: Run Cypress tests
        working-directory: qa-frontend-task
        run: npx cypress run
