name: QA CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install backend dependencies
        working-directory: ./qa-backend-task
        run: npm install

      - name: Start backend server
        working-directory: ./qa-backend-task
        run: |
          nohup npm run dev > backend.log 2>&1 &

      - name: Run Cypress tests with frontend auto-start
        uses: cypress-io/github-action@v5
        with:
          working-directory: ./qa-frontend-task
          start: npm run dev
          wait-on: http://localhost:3000
          wait-on-timeout: 60
