name: QA CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install backend dependencies
        working-directory: ./qa-backend-task
        run: npm install

      - name: Start backend
        working-directory: ./qa-backend-task
        run: |
          nohup npm run dev > backend.log 2>&1 &
          sleep 15

      - name: Install frontend dependencies
        working-directory: ./qa-frontend-task
        run: npm install

      - name: Build frontend
        working-directory: ./qa-frontend-task
        run: npm run build

      - name: Free port 3000
        run: |
          if lsof -i:3000; then
            kill -9 $(lsof -t -i:3000)
          fi

      - name: Install Cypress (at root)
        run: npm install cypress --save-dev

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./
          config-file: cypress.config.js
          start: npm start --prefix qa-frontend-task
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60

      - name: Upload Cypress screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Cypress videos on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
