name: QA CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install backend dependencies
        working-directory: ./qa-backend-task
        run: npm install

      - name: Install frontend dependencies
        working-directory: ./qa-frontend-task
        run: npm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./qa-frontend-task
          start: npm run dev
          wait-on: http://localhost:3000
          wait-on-timeout: 60
        env:
          CYPRESS_baseUrl: http://localhost:3000

      - name: Upload Cypress screenshots (on failure)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: qa-frontend-task/cypress/screenshots
